# Generated by Django 4.2.21 on 2025-10-13 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    def _set_admin_role(apps, schema_editor):
        User = apps.get_model("core", "User")
        User.objects.filter(is_superuser=True).update(role="admin")

    operations = [
        migrations.RunPython(_set_admin_role, migrations.RunPython.noop),
    ]
